---
- name: Define install user
  ansible.builtin.set_fact:
    codium_install_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  when: codium_install_user is not defined

- name: Install Codium Developer RPM Keys
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg

- name: Add yum repository for Codium
  become: true
  ansible.builtin.yum_repository:
    name: vscodium
    description: gitlab.com_paulcarroty_vscodium_repo
    baseurl: https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
    enabled: true
    gpgkey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
    gpgcheck: true

- name: Ensure VSCodium is installed
  become: true
  package:
    name: codium
    state: present

- name: Check if vscodium is registered to handle "vscode://" urls
  ansible.builtin.command: xdg-settings get default-url-scheme-handler vscode
  register: default_url_scheme_handler
  changed_when: false

- name: Ensure that vscodium is registered to handle "vscode://" urls
  ansible.builtin.command: xdg-settings set default-url-scheme-handler vscode codium-url-handler.desktop
  when: "'codium-url-handler.desktop' not in default_url_scheme_handler.stdout"

- name: Include extensions.yml tasks
  ansible.builtin.include_tasks: extensions.yml
