---
- name: VSCodium | Use OS-specifc tasks
  ansible.builtin.include_tasks: "{{ os_specific_tasks }}"
  vars:
    install_tasks_files:
      files:
        - install-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml  # noqa var-spacing
        - install-{{ ansible_distribution }}.yml
        - install-{{ ansible_os_family }}.yml
    os_specific_tasks: "{{ lookup('ansible.builtin.first_found', install_tasks_files) }}"
  when:
    - (os_specific_tasks | length > 0)

