---
- name: Import Cisco GPG Singing Key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://binaries.webex.com/WebexDesktop-CentOS-Official-Package/webex_public.key

- name: Gather the package facts
  become: true
  ansible.builtin.package_facts:
    manager: auto

- name: Install Cisco WebEx Desktop for Linux
  become: true
  ansible.builtin.yum:
    name: https://binaries.webex.com/WebexDesktop-CentOS-Official-Package/Webex.rpm
    state: present
  when: "'webex' not in ansible_facts.packages"
